spring:
  profiles:
    active: local
  application:
    name: 'rocketmq-console'
app:
  id: rocketmq-console
logging:
  #logback配置文件
  config: classpath:logback-spring.xml
  #日志文件名称
  file: 'rocketmq-console'
  #日志文件路径
  path: '/xs/logs/rocketmq-console/'
  #日志文件级别（在bootstrap文件中可以配置默认值，可以在application.yml中进行覆盖，或是在执行的profile配置中覆盖）
  #注意：不要修改此处配置，如果想修改执行环境的日志级别，可修改执行profile中的日志级别，覆盖此默认配置
  #可选配置：TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  level:
    root: INFO
server:
  port: 8081
---
spring:
  profiles: local
  datasource:
      url:  jdbc:mysql://119.23.248.65:3306/cms?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: LjtYc939487@love
      driverClassName: com.mysql.jdbc.Driver

params:
  trans-max-check-times: 15
  batch-insert-size: 50
rocketmq:
  config:
    namesrvAddr: 119.23.248.65:9876
    isVIPChannel: false
    dataPath: /tmp/rocketmq-console/data
    enableDashBoardCollect: true
    ticketKey: ticket
    loginRequired: false

---
spring:
  profiles: test

apollo:

---
spring:
     profiles: online
