spring:
  profiles:
    active: local
  application:
    name: 'rocketmq-console'
app:
  id: rocketmq-console
apollo:
  cacheDir: '/xs/webapps/rocketmq-console/apollo/'
  bootstrap:
    enabled: true
logging:
  #logback配置文件
  config: classpath:logback-spring.xml
  #日志文件名称
  file: 'rocketmq-console'
  #日志文件路径
  path: '/xs/logs/rocketmq-console/'
  #日志文件级别（在bootstrap文件中可以配置默认值，可以在application.yml中进行覆盖，或是在执行的profile配置中覆盖）
  #注意：不要修改此处配置，如果想修改执行环境的日志级别，可修改执行profile中的日志级别，覆盖此默认配置
  #可选配置：TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  level:
    root: INFO
---
spring:
  profiles: local
apollo:
  cluster: default
  meta: http://test.apollo.xs.sit
---
spring:
  profiles: test

apollo:
  cluster: test
  meta: http://test.apollo.xs.sit
---
spring:
     profiles: online
apollo:
  cluster: default
  meta: http://apollo.config.xs.prd